title: "Build an Opensearch demo using DevOps"
stackDescription: "Build an Opensearch demo using DevOps" 
description: "Build an Opensearch demo using DevOps"
schemaVersion: 1.1.0
version: "20220919"
locale: "en"

#################
# Variable Groups
#################
variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - compartment_ocid
  - region
  - network_cidrs
  - repository_repository_type
  - release


- title: Required Configuration
  visible: true  
  variables:
    - oci_username
    - oci_user_authtoken
    - show_advanced

- title: DevOps Project Configuration
  visible: true  
  variables:
    - compartment_id
    - app_name


#################
# Output Groups
#################


######################
# Variable Definitions
######################

variables:

# Required

  oci_username:
    type: string
    required: true
    visibile: true
    title: "OCI username"
    description: "For a federated user (single sign-on with an identity provider), enter the username in the following format: TenancyName/Federation/UserName. For example, if you use OCI's identity provider, your login would be, Acme/oracleidentitycloudservice/alice.jones@acme.com. If you are using OCI's direct sign-in, enter the username in the following format: TenancyName/YourUserName. For example, Acme/alice_jones. Your password is the auth token you created previously."

  oci_user_authtoken:
    type: password
    required: true
    visibile: true
    title: "OCI user auth token"
    description: "You can get the auth token from your Profile menu -> click User Settings -> On left side  click *Auth Tokens -> Generate Token"
  
  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  compartment_id: 
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create resources"
    required: true

  app_name:
    type: string
    title: "Project Name"
    required: true

  public_ssh_key:
    type: oci:core:ssh:publickey
    title: "Import your own SSH public key"
    additionalProps:
      allowMultiple: true
    required: false
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
    visible:
      and:
        - and:
          - show_advanced
        - not:
          - generate_public_ssh_key

  existent_dynamic_group_for_nodes_in_compartment:
    type: string
    required: false
    title: "Existent Dynamic Group"
    visible:
      and:
        - and:
          - show_advanced
        - or:
          - create_compartment_policies
          - create_tenancy_policies
        - not:
          - create_dynamic_group_for_nodes_in_compartment
        
  create_compartment_policies:
    type: boolean
    title: "Create Compartment Policies"
    required: false
    visible:
      and:
        - show_advanced

  create_tenancy_policies:
    type: boolean
    title: "Create Tenancy Policies"
    required: false
    visible:
      and:
        - show_advanced

  container_repository_is_public:
    type: boolean
    title: "Is Container Repository public?"
    required: false
    visible: true  

  registry_display_name:
    type: string
    title: "Registry Display Name"
    description: "Registry Display Name"
    required: false
    visible: true
  

  build_pipeline_stage_is_pass_all_parameters_enabled:
    type: boolean
    title: "Build Pipeline Stage: is pass all parameters enabled?"
    description: "DevOps Build Pipeline Deploy Stage - enable passing all parameters." 
    required: false
    visible: true

